#!/usr/bin/python
# -*- mode: python; coding: koi8-r -*-
#
# (c) Vitaly Tonkacheyev, 2010
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

import os
import threading, thread
try:
    import pygtk
    pygtk.require('2.0')
    import gtk
except:
    sys.stderr.write("Error#001: No Gtk Module Found in pyAlsaVolume module\n")
    sys.exit(1)

from pyAlsaVolume.pySliderFrame import SliderFrame
  
if __name__ == "__main__":
    gtk.gdk.threads_init()
    gtk.gdk.threads_enter()
    app = SliderFrame()
    gtk.main()
    gtk.gdk.threads_leave()
