#!/usr/bin/env python
#-*- coding: utf-8 -*-
# Rewritten for use Gtk+3
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GObject, Gdk, GLib
import os, re, string, threading, html

try:
    from chardet.universaldetector import UniversalDetector
except:
    os.sys.stderr.write("Error! No Module python-chardet found.")
    os.sys.exit(1)

INFO=Gtk.MessageType.INFO
ERROR=Gtk.MessageType.ERROR

class ConvertThread(threading.Thread):
    """thread class"""
    def __init__(self, parent):
        super(ConvertThread,  self).__init__()
        self.parent = parent

    def run(self):
        if self.parent.WalkOn():
            GLib.idle_add(self.parent.JobFinished)

class msgDialog(Gtk.MessageDialog):
    def __init__(self, parent, message, typeOf):
        Gtk.MessageDialog.__init__(self,
                                   parent=parent,
                                   modal=True,
                                   destroy_with_parent=True,
                                   message_type=typeOf,
                                   buttons=Gtk.ButtonsType.OK,
                                   text=str(message)
                                   )
        self.connect('response', self._handle_clicked)

    def _handle_clicked(self, *args):
        self.destroy()

    def show_dialog(self):
        GLib.timeout_add(0, self._do_show_dialog)

    def _do_show_dialog(self):
        self.show()
        return False

class mainForm:
    def __init__(self):
        self.files = []
        self.done = False
        self.ismanual = False
        self.txtencoding = ""
        self.htmlencoding = ""
        self.job = None
        self.isError = False
        self.ignoreErrors = False
        self.wasError = False
        self.tags = re.compile(r'<[^<]*?/?>', re.IGNORECASE)
        self.adtag = re.compile(r'<[^<]*?/?>|(?:&.*?;)', re.IGNORECASE)
        self.tags_re = re.compile(r'(<!--.*?-->|<[^>]*>)', re.IGNORECASE)
        self.tgs = re.compile(r'<[^>]+>', re.IGNORECASE)
        self.empty = re.compile(r'^(?:\s)*$', re.MULTILINE)
        self.filter = Gtk.FileFilter()
        self.filter.add_pattern("*.html")
        self.filter.add_pattern("*.htm")
        if str(os.sys.platform) == 'win32' or os.path.exists('main_win.glade'):
            gladefile = 'main_win.glade'
        elif  os.path.exists('/usr/share/htmltotextgui/main_win.glade') :
            gladefile = '/usr/share/htmltotextgui/main_win.glade'
        else:
            gladefile = os.environ['HOME']+'/.local/share/htmltotextgui/main_win.glade'
        if os.path.exists(gladefile):
            self.builder = Gtk.Builder()
            self.builder.add_from_file(gladefile)
        else:
            os.sys.stderr.write('Error No %s file found' %gladefile)
            os.sys.exit(1)
        dic = {"on_mainForm_destroy_event": self.OnDestroy, "on_mainForm_delete_event": self.OnDestroy,
               "on_filechooser_selection_changed": self.OnFile, "on_runit_pressed":self.OnRun,
               "on_charselect_changed": self.OnCharSelect,  "on_automat_toggled": self.OnAutomat,
               "on_manual_toggled":self.OnManual, "on_htmlchar_changed": self.OnHtmlChar, "on_ignorecheck_toggled": self.isErrorIgnore }
        self.builder.get_objects()
        self.builder.connect_signals(dic)
        self.mainForm = self.builder.get_object("mainForm")
        self.charselect = self.builder.get_object("charselect")
        self.htmlchar = self.builder.get_object("htmlchar")
        self.ignorecheck = self.builder.get_object("ignorecheck")
        self.ignorecheck.set_active(1)
        self.charselect.set_entry_text_column(0)
        self.charselect.set_active(0)
        self.htmlchar.set_entry_text_column(0)
        self.htmlchar.set_active(0)
        self.progress = self.builder.get_object("progress")
        self.automat = self.builder.get_object("automat")
        self.manual = self.builder.get_object("manual")
        self.automat.toggled()
        self.filechooser = self.builder.get_object("filechooser")
        self.filechooser.set_filter(self.filter)
        self.button = self.builder.get_object("runit")
        self.sens_objects = (self.automat, self.manual, self.filechooser, self.charselect, self.button,  self.ignorecheck)
        self.mainForm.show_all()
        self.work = None
        self.job_finished = False

    def OnAutomat(self,  widget):
        if widget.get_active():
            self.htmlchar.set_sensitive(False)
            self.ismanual = False

    def OnManual(self,  widget):
        if widget.get_active():
            self.htmlchar.set_sensitive(True)
            self.ismanual = True

    def OnHtmlChar(self,  widget) :
        self.htmlencoding = widget.get_active_text()
        print (self.htmlencoding)

    def OnFile(self, widget):
        self.files = []
        self.files = widget.get_filenames()

    def OnRun(self, widget):
        self.setSensitive(False)
        self.work = ConvertThread(self)
        self.work.start()

    def OnCharSelect(self, widget):
        self.txtencoding = widget.get_active_text()
        print (self.txtencoding)

    def OnDestroy(self, widget, event):
        Gtk.main_quit()
        return True

    def isErrorIgnore(self, widget):
        self.ignoreErrors = widget.get_active()

    def WalkOn(self):
        files = self.files
        outencoding = self.charselect.get_active_text()
        encoding = ""
        if files:
            for item in files:
                GLib.idle_add(self.SetText, files.index(item), len(files), "Converting file %s..."%item)
                if item:
                    lines = []
                    enc_lines = []
                    outtext = []
                    lines = self.readFile(item)
                    if self.ismanual:
                        encoding = self.htmlencoding
                        try:
                            enc_lines.append(self.JoinStr(lines).decode(encoding))
                        except Exception as  error:
                            if str(os.sys.platform) != 'win32':
                                os.sys.stderr.write(str(error)+"\n")
                            if not self.ignoreErrors:
                                GLib.idle_add(self.on_info, "There was an Error when decoding file\n%s"%item, ERROR)
                            continue
                    else:
                        enc_lines.append(self.JoinStr(lines))
                    txtfile = self.GetFilename(item) + "txt"
                    outtext = self.RemoveTAGS(self.JoinStr(enc_lines), item, outencoding)
                    if self.isError:
                        self.wasError = True
                    if str(os.sys.platform) == 'win32':
                        txtfile = txtfile.decode('UTF-8')
                    self.writeFile(txtfile,  str(outtext))
            return True

    def JobFinished(self):
            self.SetText(1,1,"Job Finished!")
            self.job_finished = True
            if self.wasError:
                self.on_info("Job Finished With Errors", INFO)
            else:
                self.on_info("Job Finished", INFO)
            self.setSensitive(True)
            self.job_finished = False

    def JoinStr(self, lines):
        return ''.join(lines)

    def SetText(self, index, total, text):
        value = float(index)/float(total)
        self.progress.set_fraction(value)
        self.progress.set_text(text)

    def RemoveTAGS(self, text, htmlfile, enc):
        notags = self.tags_re.sub('', text)
        extra = self.tags.sub('', notags)
        adextra = self.adtag.sub('', extra)
        remextra = html.unescape(adextra)
        return remextra

    #def RemoveEmptyLines(self, text, enc):
    #    nonemptyresult = []
    #    for line in text.split("\n"):
    #        if not self.isEmptyLine(line):
    #            tmpline = []
    #            try:
    #                tmpline.append(line)
    #                if ord(line[-1:]) != 13:
    #                    tmpline.append("\n")
    #                resultline = self.JoinStr(tmpline)
    #                if enc != None:
    #                    print(enc)
    #                    nonemptyresult.append(resultline.encode(enc))
    #                else:
    #                    nonemptyresult.append(resultline)
    #            except Exception as  error:
    #                if not self.ignoreErrors:
    #                    GLib.idle_add(self.on_info, "There was an Error %s"%str(error), ERROR)
    #                self.isError = True
    #    return nonemptyresult

    def isEmptyLine(self, line):
        return len(line.strip()) == 0

    def writeFile(self,  filename,  text):
        fl = open(filename, "w")
        fl.seek(0)
        fl.writelines(text)
        fl.close()

    def readFile(self, filename):
        result = []
        mode="r"
        detector = UniversalDetector() #load encoding detector
        if str(os.sys.platform) == 'win32':
            filename = filename.decode('UTF-8')
            mode="rb"
        for line in open(filename, "rb"): #read file as bytes to detect encoding
            detector.feed(line)
            if detector.done: break
        detector.close()
        encoding = detector.result['encoding']
        if encoding == 'MacCyrillic':
            encoding = 'windows-1251'
        with open(filename, mode=mode, encoding=encoding) as f: #open file as text with encoding
            result = f.readlines()
            f.close()
        return result

    def on_info(self, text, typeOf):
        if (self.mainForm):
            dialog=msgDialog(self.mainForm, text, typeOf)
            dialog.show_dialog()
            if self.job_finished:
                self.SetText(0,100,"0%")

    def setSensitive(self,  state):
        for i in self.sens_objects:
            if i != None:
                i.set_sensitive(state)

    def GetFilename(self, htmlfile):
        if htmlfile:
            if htmlfile[-4:] == "html":
                if htmlfile[-5] == ".":
                    return htmlfile[0: len(htmlfile)-4]
            elif htmlfile[-3:] == "htm":
                if htmlfile[-4] == ".":
                    return htmlfile[0: len(htmlfile)-3]
            else:
                return ""
        else:
            return ""

if __name__ == "__main__":
    app = mainForm()
    Gtk.main()
