#!/usr/bin/env python
#-*- coding: utf-8 -*-
# Rewritten for use Gtk+3

from gi.repository import Gtk, GObject, Gdk, GLib
import os, re, string, threading, HTMLParser

try:
    from chardet.universaldetector import UniversalDetector
except:
    os.sys.stderr.write("Error! No Module python-chardet found.")
    os.sys.exit(1)

INFO=Gtk.MessageType.INFO
ERROR=Gtk.MessageType.ERROR

class MLStripper(HTMLParser.HTMLParser):
    def __init__(self):
        self.reset()
        self.fed = []
    def handle_data(self, d):
        self.fed.append(d)
    def get_fed_data(self):
        return ''.join(self.fed)

class ConvertThread(threading.Thread):
    """thread class"""
    def __init__(self, parent):
        super(ConvertThread,  self).__init__()
        self.parent = parent

    def run(self):
        if self.parent.WalkOn():
            self.parent.JobFinished()

class msgDialog(Gtk.MessageDialog):
    def __init__(self, parent, message, typeOf):
        Gtk.MessageDialog.__init__(self, parent, Gtk.DialogFlags.MODAL | Gtk.DialogFlags.DESTROY_WITH_PARENT,
                                typeOf, Gtk.ButtonsType.OK, message)
        self.set_default_response(Gtk.ResponseType.OK)
        self.connect('response', self._handle_clicked)

    def _handle_clicked(self, *args):
        self.destroy()

    def show_dialog(self):
        GObject.timeout_add(0, self._do_show_dialog)

    def _do_show_dialog(self):
        self.show_all()
        return False

class mainForm:
    def __init__(self):
        self.files = []
        self.done = False
        self.ismanual = False
        self.txtencoding = ""
        self.htmlencoding = ""
        self.job = None
        self.isError = False
        self.ignoreErrors = False
        self.wasError = False
        self.tags = re.compile(r'<[^<]*?/?>', re.IGNORECASE)
        self.adtag = re.compile(r'<[^<]*?/?>|(?:&.*?;)', re.IGNORECASE)
        self.empty = re.compile(r'^(?:\s)*$', re.MULTILINE)
        self.filter = Gtk.FileFilter()
        self.filter.add_pattern("*.html")
        self.filter.add_pattern("*.htm")
        if str(os.sys.platform) == 'win32':
            gladefile = 'main_win.glade'
        elif  os.path.exists('/usr/share/htmltotextgui/main_win.glade') :
            gladefile = '/usr/share/htmltotextgui/main_win.glade'
        else:
            gladefile = os.environ['HOME']+'/.local/share/htmltotextgui/main_win.glade'
        if os.path.exists(gladefile):
            self.builder = Gtk.Builder()
            self.builder.add_from_file(gladefile)
        else:
            os.sys.stderr.write('Error No %s file found' %gladefile)
            os.sys.exit(1)
        dic = {"on_mainForm_destroy_event": self.OnDestroy, "on_mainForm_delete_event": self.OnDestroy,
               "on_filechooser_selection_changed": self.OnFile, "on_runit_pressed":self.OnRun,
               "on_charselect_changed": self.OnCharSelect,  "on_automat_toggled": self.OnAutomat,
               "on_manual_toggled":self.OnManual, "on_htmlchar_changed": self.OnHtmlChar, "on_ignorecheck_toggled": self.isErrorIgnore }
        self.builder.get_objects()
        self.builder.connect_signals(dic)
        self.mainForm = self.builder.get_object("mainForm")
        self.charselect = self.builder.get_object("charselect")
        self.htmlchar = self.builder.get_object("htmlchar")
        self.ignorecheck = self.builder.get_object("ignorecheck")
        self.ignorecheck.set_active(1)
        self.charselect.set_entry_text_column(0)
        self.charselect.set_active(0)
        self.htmlchar.set_entry_text_column(0)
        self.htmlchar.set_active(0)
        self.progress = self.builder.get_object("progress")
        self.automat = self.builder.get_object("automat")
        self.manual = self.builder.get_object("manual")
        self.automat.toggled()
        self.filechooser = self.builder.get_object("filechooser")
        self.filechooser.set_filter(self.filter)
        self.button = self.builder.get_object("runit")
        self.sens_objects = (self.automat, self.manual, self.filechooser, self.charselect, self.button,  self.ignorecheck)
        self.mainForm.show_all()
        self.work = None
        self.job_finished = False

    def OnAutomat(self,  widget):
        if widget.get_active():
            self.htmlchar.set_sensitive(False)
            self.ismanual = False

    def OnManual(self,  widget):
        if widget.get_active():
            self.htmlchar.set_sensitive(True)
            self.ismanual = True

    def OnHtmlChar(self,  widget) :
        self.htmlencoding = widget.get_active_text()
        print (self.htmlencoding)

    def OnFile(self, widget):
        self.files = []
        self.files = widget.get_filenames()

    def OnRun(self, widget):
        self.setSensitive(False)
        self.work = ConvertThread(self)
        self.work.start()

    def OnCharSelect(self, widget):
        self.txtencoding = widget.get_active_text()
        print (self.txtencoding)

    def OnDestroy(self, widget, event):
        Gtk.main_quit()
        return True

    def isErrorIgnore(self, widget):
        self.ignoreErrors = widget.get_active()

    def WalkOn(self):
        files = self.files
        outencoding = self.charselect.get_active_text()
        encoding = ""
        if files:
            for item in files:
                Gdk.threads_enter()
                self.SetText(files.index(item), len(files), "Converting file %s..."%item)
                Gdk.threads_leave()
                if item != None:
                    lines = []
                    enc_lines = ""
                    outtext = []
                    lines = self.readFile(item)
                    if not self.ismanual:
                        encoding = self.Decode(lines)
                        if encoding == 'MacCyrillic':
                            encoding = 'windows-1251'
                        print(encoding)
                    else:
                        encoding = self.htmlencoding
                    if encoding != None:
                        try:
                            enc_lines = "".join(lines).decode(encoding)
                        except Exception as  error:
                            if str(os.sys.platform) != 'win32':
                                os.sys.stderr.write(str(error)+"\n")
                            if not self.ignoreErrors:
                                Gdk.threads_enter()
                                self.on_info("There was an Error when decoding file\n%s"%item, ERROR)
                                Gdk.threads_leave()
                            continue
                    else:
                        continue
                    txtfile = self.GetFilename(item) + "txt"
                    outtext = self.RemoveTAGS(enc_lines, item, outencoding)
                    if self.isError:
                        self.wasError = True
                    if str(os.sys.platform) == 'win32':
                        txtfile = txtfile.decode('UTF-8')
                    self.writeFile(txtfile,  outtext)
            return True

    def JobFinished(self):
            self.SetText(1,1,"Job Finished!")
            self.job_finished = True
            if self.wasError:
                self.on_info("Job Finished With Errors", INFO)
            else:
                self.on_info("Job Finished", INFO)
            self.setSensitive(True)
            self.job_finished = False


    def SetText(self, index, total, text):
        value = float(index)/float(total)
        self.progress.set_fraction(value)
        self.progress.set_text(text)

    def RemoveTAGS(self, text, htmlfile, enc):
        try:
            tmp1 = MLStripper()
            tmp1.feed(text)
            tmp2 = tmp1.get_fed_data()
            tmp3 = self.tags.sub('',  tmp2)
            self.isError = False
            return self.RemoveEmptyLines(tmp3, enc)
        except HTMLParser.HTMLParseError as msg:
            self.isError = True
            error = str(msg) + "\nin file:\n" + str(htmlfile)
            if str(os.sys.platform) != 'win32':
                os.sys.stderr.write(str(error)+"\n")
            if not self.ignoreErrors:
                Gdk.threads_enter()
                self.on_info("Error in HTMLParser module. Wrong tag\n%s\n\nTags will be removed using regular expressions\nThere are rubbish possible in TXT file"%error, ERROR)
                Gdk.threads_leave()
            tmp4 = self.adtag.sub('',text)
            return self.RemoveEmptyLines(tmp4, enc)

    def RemoveEmptyLines(self, text, enc):
        lines = string.split(text, '\n')
        result = []
        for line in lines:
            if line.strip():
                if self.empty.search(line):
                    continue
                else:
                    try:
                        if ord(line[-1:]) == 13:
                            result.append(line.encode(enc))
                        else:
                            result.append((line+'\n').encode(enc))
                    except Exception as  error:
                            #if str(os.sys.platform) != 'win32':
                                #os.sys.stderr.write(str(error)+"\n")
                            if not self.ignoreErrors:
                                Gdk.threads_enter()
                                self.on_info("There was an Error %s"%str(error), ERROR)
                                Gdk.threads_leave()
                            self.isError = True
        return result

    def writeFile(self,  filename,  text):
        fl = open(filename, "w")
        fl.seek(0)
        fl.writelines(text)
        fl.close()

    def readFile(self, filename):
        result = []
        if str(os.sys.platform) == 'win32':
            filename = filename.decode('UTF-8')
        f = open(filename, "rb")
        f.seek(0)
        for line in f.readlines():
            if line:
                result.append(line)
        f.close()
        return result

    def on_info(self, text, typeOf):
        if (self.mainForm):
            dialog=msgDialog(self.mainForm, text, typeOf)
            dialog.show_dialog()
            if self.job_finished:
                self.SetText(0,100,"0%")

    def setSensitive(self,  state):
        for i in self.sens_objects:
            if i != None:
                i.set_sensitive(state)

    def GetFilename(self, htmlfile):
        if htmlfile:
            if htmlfile[-4:] == "html":
                if htmlfile[-5] == ".":
                    return htmlfile[0: len(htmlfile)-4]
            elif htmlfile[-3:] == "htm":
                if htmlfile[-4] == ".":
                    return htmlfile[0: len(htmlfile)-3]
            else:
                return ""
        else:
            return ""

    def Decode(self, lines):
        try:
            detector = UniversalDetector()
            for line in lines:
                detector.feed(line)
                if detector.done: break
            detector.close()
            tmp = detector.result
            result = tmp['encoding']
        except:
            return None
        return result

if __name__ == "__main__":
    GLib.threads_init()
    Gdk.threads_init()
    Gdk.threads_enter()
    app = mainForm()
    Gtk.main()
    Gdk.threads_leave()
