; Shared component restoration list for the Psi+ NSIS installer.
; Include this file after all plugin and dictionary sections have been declared.

!macro RESTORE_ALL_PLUGIN_COMPONENTS
  !insertmacro RESTORE_COMPONENT attentionplugin
  !insertmacro RESTORE_COMPONENT autoreplyplugin
  !insertmacro RESTORE_COMPONENT battleshipgameplugin
  !insertmacro RESTORE_COMPONENT birthdayreminderplugin
  !insertmacro RESTORE_COMPONENT chessplugin
  !insertmacro RESTORE_COMPONENT cleanerplugin
  !insertmacro RESTORE_COMPONENT clientswitcherplugin
  !insertmacro RESTORE_COMPONENT conferenceloggerplugin
  !insertmacro RESTORE_COMPONENT contentdownloaderplugin
  !insertmacro RESTORE_COMPONENT enummessagesplugin
  !insertmacro RESTORE_COMPONENT extendedmenuplugin
  !insertmacro RESTORE_COMPONENT extendedoptionsplugin
  !insertmacro RESTORE_COMPONENT gomokugameplugin
  !insertmacro RESTORE_COMPONENT historykeeperplugin
  !insertmacro RESTORE_COMPONENT imageplugin
  !insertmacro RESTORE_COMPONENT imagepreviewplugin
  !insertmacro RESTORE_COMPONENT jabberdiskplugin
  !insertmacro RESTORE_COMPONENT juickplugin
  !insertmacro RESTORE_COMPONENT mediaplugin
  !insertmacro RESTORE_COMPONENT messagefilterplugin
  !insertmacro RESTORE_COMPONENT noughtsandcrossesplugin
  !insertmacro RESTORE_COMPONENT openpgpplugin
  !insertmacro RESTORE_COMPONENT otrplugin
  !insertmacro RESTORE_COMPONENT pepchangenotifyplugin
  !insertmacro RESTORE_COMPONENT qipxstatusesplugin
  !insertmacro RESTORE_COMPONENT redirectorplugin
  !insertmacro RESTORE_COMPONENT skinsplugin
  !insertmacro RESTORE_COMPONENT stopspamplugin
  !insertmacro RESTORE_COMPONENT storagenotesplugin
  !insertmacro RESTORE_COMPONENT translateplugin
  !insertmacro RESTORE_COMPONENT videostatusplugin
  !insertmacro RESTORE_COMPONENT watcherplugin
!macroend

!macro RESTORE_ALL_DICTIONARY_COMPONENTS
  !insertmacro RESTORE_DICT af_ZA
  !insertmacro RESTORE_DICT an_ES
  !insertmacro RESTORE_DICT ar
  !insertmacro RESTORE_DICT be_BY
  !insertmacro RESTORE_DICT bg_BG
  !insertmacro RESTORE_DICT bn_BD
  !insertmacro RESTORE_DICT br_FR
  !insertmacro RESTORE_DICT bs_BA
  !insertmacro RESTORE_DICT cs_CZ
  !insertmacro RESTORE_DICT da_DK
  !insertmacro RESTORE_DICT de_AT_frami
  !insertmacro RESTORE_DICT de_CH_frami
  !insertmacro RESTORE_DICT de_DE_frami
  !insertmacro RESTORE_DICT el_GR
  !insertmacro RESTORE_DICT en_AU
  !insertmacro RESTORE_DICT en_CA
  !insertmacro RESTORE_DICT en_GB
  !insertmacro RESTORE_DICT en_US
  !insertmacro RESTORE_DICT en_ZA
  !insertmacro RESTORE_DICT es_ANY
  !insertmacro RESTORE_DICT et_EE
  !insertmacro RESTORE_DICT fr
  !insertmacro RESTORE_DICT gl_ES
  !insertmacro RESTORE_DICT gu_IN
  !insertmacro RESTORE_DICT he_IL
  !insertmacro RESTORE_DICT hi_IN
  !insertmacro RESTORE_DICT hr_HR
  !insertmacro RESTORE_DICT hu_HU
  !insertmacro RESTORE_DICT is_dic
  !insertmacro RESTORE_DICT it_IT
  !insertmacro RESTORE_DICT kmr_Latn
  !insertmacro RESTORE_DICT lo_LA
  !insertmacro RESTORE_DICT lt
  !insertmacro RESTORE_DICT lv_LV
  !insertmacro RESTORE_DICT nb_NO
  !insertmacro RESTORE_DICT ne_NP
  !insertmacro RESTORE_DICT nl_NL
  !insertmacro RESTORE_DICT nn_NO
  !insertmacro RESTORE_DICT oc_FR
  !insertmacro RESTORE_DICT pl_PL
  !insertmacro RESTORE_DICT pt_BR
  !insertmacro RESTORE_DICT pt_PT
  !insertmacro RESTORE_DICT ro_RO
  !insertmacro RESTORE_DICT ru_RU
  !insertmacro RESTORE_DICT si_LK
  !insertmacro RESTORE_DICT sk_SK
  !insertmacro RESTORE_DICT sl_SI
  !insertmacro RESTORE_DICT sr_Latn
  !insertmacro RESTORE_DICT sr
  !insertmacro RESTORE_DICT sv_FI
  !insertmacro RESTORE_DICT sv_SE
  !insertmacro RESTORE_DICT sw_TZ
  !insertmacro RESTORE_DICT te_IN
  !insertmacro RESTORE_DICT th_TH
  !insertmacro RESTORE_DICT uk_UA
  !insertmacro RESTORE_DICT vi_VN
!macroend
